# Bizarre Paper for Foot
font=Monaspace Neon:size=13

[colors]
background=F9F8F2
foreground=1F1F1F
regular0=1A1A1A
regular1=C13039
regular2=3F7A1F
regular3=9F4A0E
regular4=1F4FB0
regular5=7E2A9A
regular6=0F6E6E
regular7=545454
bright0=726D61
bright1=C63947
bright2=4A7409
bright3=94631C
bright4=386EB6
bright5=95559F
bright6=397777
bright7=0E0E0E
selection-foreground=0E0E0E
selection-background=DCEFA8
urls=1F4FB0
