# Bizarre Void for Foot
font=Monaspace Neon:size=13

[colors]
background=0E0E0E
foreground=E4E4E4
regular0=1A1A1A
regular1=F0525B
regular2=3FB950
regular3=E8A33D
regular4=5B9FFF
regular5=D88AE0
regular6=7AD9D9
regular7=E4E4E4
bright0=3D3D3D
bright1=FF6F77
bright2=C6FF24
bright3=FFB85C
bright4=7BB3FF
bright5=E8A8EE
bright6=9DEAEA
bright7=FFFFFF
selection-foreground=F9F8F2
selection-background=2B3A0E
urls=7BB3FF
