[theme]
name = "bizarre-void"

[colors]
AlertInfo = "#7BB3FF"
AlertWarn = "#FFB85C"
AlertError = "#FF6F77"
Annotation = "#7A7A7A"
Base = "#E4E4E4"
Guidance = "#7BB3FF"
Important = "#C6FF24"
Title = "#C6FF24"
Muted = "#545454"
