# Bizarre Void Hi-Contrast for Hyprland
$bizarre_bg = rgb(000000)
$bizarre_fg = rgb(F9F8F2)
$bizarre_accent = rgb(C6FF24)
$bizarre_border = rgb(545454)

general {
  col.active_border = rgba(C6FF24ff)
  col.inactive_border = rgba(545454cc)
}

decoration {
  rounding = 6
  shadow {
    color = rgba(000000dd)
    color_inactive = rgba(0E0E0Eaa)
  }
}

group {
  col.border_active = rgba(C6FF24ff)
  col.border_inactive = rgba(545454ff)
  groupbar {
    col.active = rgba(C6FF24ff)
    col.inactive = rgba(0E0E0Eff)
    text_color = rgba(F9F8F2ff)
  }
}
