# Bizarre Paper - Kitty
font_family Monaspace Neon
foreground #1F1F1F
background #F9F8F2
selection_foreground #0E0E0E
selection_background #DCEFA8
cursor #5F8A0F
cursor_text_color #0E0E0E
url_color #1F4FB0
active_tab_foreground #0E0E0E
active_tab_background #5F8A0F
inactive_tab_foreground #3D3D3D
inactive_tab_background #F2F0EA
tab_bar_background #F9F8F2
color0 #1A1A1A
color1 #C13039
color2 #3F7A1F
color3 #9F4A0E
color4 #1F4FB0
color5 #7E2A9A
color6 #0F6E6E
color7 #545454
color8 #726D61
color9 #C63947
color10 #4A7409
color11 #94631C
color12 #386EB6
color13 #95559F
color14 #397777
color15 #0E0E0E
