# Bizarre Paper for Foot
font=Monaspace Neon:size=13

[colors]
background=F9F8F2
foreground=1F1F1F
regular0=1A1A1A
regular1=C13039
regular2=3F7A1F
regular3=9F4A0E
regular4=1F4FB0
regular5=7E2A9A
regular6=0F6E6E
regular7=545454
bright0=7A7568
bright1=E04050
bright2=5F8A0F
bright3=C28225
bright4=3D78C7
bright5=A55EAF
bright6=4FA3A3
bright7=0E0E0E
selection-foreground=0E0E0E
selection-background=DCEFA8
urls=1F4FB0
