[theme]
name = "bizarre-void-hicontrast"

[colors]
AlertInfo = "#7BB3FF"
AlertWarn = "#FFB85C"
AlertError = "#FF6F77"
Annotation = "#B8B8B8"
Base = "#F9F8F2"
Guidance = "#7BB3FF"
Important = "#C6FF24"
Title = "#C6FF24"
Muted = "#B8B8B8"
