[theme]
name = "bizarre-paper"

[colors]
AlertInfo = "#1F4FB0"
AlertWarn = "#97460D"
AlertError = "#AC2468"
Annotation = "#3D3D3D"
Base = "#1F1F1F"
Guidance = "#1F4FB0"
Important = "#4A7409"
Title = "#4A7409"
Muted = "#3D3D3D"
