[theme]
name = "bizarre-bone"

[colors]
AlertInfo = "#1F4FB0"
AlertWarn = "#97460D"
AlertError = "#AC2468"
Annotation = "#4A4A4A"
Base = "#2B2B2B"
Guidance = "#1F4FB0"
Important = "#4A7409"
Title = "#4A7409"
Muted = "#4A4A4A"
