-- Bizarre Industries — highlight groups
local M = {}

local function set(groups)
  for k, v in pairs(groups) do vim.api.nvim_set_hl(0, k, v) end
end

function M.apply(p)
  set({
    -- ── editor surfaces ──
    Normal       = { fg = p.fg, bg = p.bg },
    NormalFloat  = { fg = p.fg, bg = p.bg2 },
    NormalNC     = { fg = p.fg, bg = p.bg },
    FloatBorder  = { fg = p.border, bg = p.bg2 },
    FloatTitle   = { fg = p.accent, bg = p.bg2, bold = true },
    SignColumn   = { bg = p.bg },
    LineNr       = { fg = p.fg4 },
    CursorLineNr = { fg = p.accent, bold = true },
    CursorLine   = { bg = p.lineHL },
    CursorColumn = { bg = p.lineHL },
    ColorColumn  = { bg = p.bg2 },
    Cursor       = { fg = p.bg, bg = p.accent },
    lCursor      = { fg = p.bg, bg = p.accent },
    TermCursor   = { fg = p.bg, bg = p.accent },
    Visual       = { bg = p.selBg },
    VisualNOS    = { bg = p.selBg },
    Search       = { fg = p.bg, bg = p.accent },
    IncSearch    = { fg = p.bg, bg = p.accent2, bold = true },
    CurSearch    = { fg = p.bg, bg = p.accent2, bold = true },
    Substitute   = { fg = p.bg, bg = p.warn },
    MatchParen   = { fg = p.accent, bold = true, underline = true },
    NonText      = { fg = p.bg3 },
    Whitespace   = { fg = p.bg3 },
    SpecialKey   = { fg = p.bg3 },
    Conceal      = { fg = p.fg3 },
    EndOfBuffer  = { fg = p.bg },
    Folded       = { fg = p.fg3, bg = p.bg2 },
    FoldColumn   = { fg = p.fg4, bg = p.bg },
    VertSplit    = { fg = p.border, bg = p.bg },
    WinSeparator = { fg = p.border, bg = p.bg },

    -- ── popups / cmdline ──
    Pmenu          = { fg = p.fg, bg = p.bg2 },
    PmenuSel       = { fg = p.bg, bg = p.accent, bold = true },
    PmenuSbar      = { bg = p.bg3 },
    PmenuThumb     = { bg = p.fg4 },
    PmenuKind      = { fg = p.type, bg = p.bg2 },
    PmenuKindSel   = { fg = p.bg, bg = p.accent, bold = true },
    PmenuExtra     = { fg = p.fg3, bg = p.bg2 },
    PmenuExtraSel  = { fg = p.bg, bg = p.accent },
    WildMenu       = { fg = p.bg, bg = p.accent },
    Question       = { fg = p.accent },
    MoreMsg        = { fg = p.success },
    ModeMsg        = { fg = p.fg, bold = true },
    ErrorMsg       = { fg = p.danger, bold = true },
    WarningMsg     = { fg = p.warn },
    Title          = { fg = p.accent, bold = true },
    Directory      = { fg = p.type, bold = true },

    -- ── status / tabs ──
    StatusLine     = { fg = p.fg, bg = p.bg2 },
    StatusLineNC   = { fg = p.fg3, bg = p.bg2 },
    TabLine        = { fg = p.fg3, bg = p.bg2 },
    TabLineFill    = { bg = p.bg2 },
    TabLineSel     = { fg = p.bg, bg = p.accent, bold = true },
    WinBar         = { fg = p.fg2, bg = p.bg },
    WinBarNC       = { fg = p.fg3, bg = p.bg },

    -- ── diff ──
    DiffAdd        = { fg = p.success, bg = p.bg },
    DiffChange     = { fg = p.warn, bg = p.bg },
    DiffDelete     = { fg = p.danger, bg = p.bg },
    DiffText       = { fg = p.fg, bg = p.bg2, bold = true },

    -- ── spelling ──
    SpellBad   = { sp = p.danger, undercurl = true },
    SpellCap   = { sp = p.warn, undercurl = true },
    SpellLocal = { sp = p.info, undercurl = true },
    SpellRare  = { sp = p.constant, undercurl = true },

    -- ── classic syntax ──
    Comment        = { fg = p.comment, italic = true },
    SpecialComment = { fg = p.fg3, italic = true },
    Constant       = { fg = p.constant },
    String         = { fg = p.string },
    Character      = { fg = p.string },
    Number         = { fg = p.number },
    Boolean        = { fg = p.number },
    Float          = { fg = p.number },
    Identifier     = { fg = p.fg },
    Function       = { fg = p.func },
    Statement      = { fg = p.keyword },
    Conditional    = { fg = p.keyword },
    Repeat         = { fg = p.keyword },
    Label          = { fg = p.keyword },
    Operator       = { fg = p.fg3 },
    Keyword        = { fg = p.keyword },
    Exception      = { fg = p.danger },
    PreProc        = { fg = p.constant },
    Include        = { fg = p.keyword, italic = true },
    Define         = { fg = p.keyword, italic = true },
    Macro          = { fg = p.constant, italic = true },
    PreCondit      = { fg = p.constant },
    Type           = { fg = p.type },
    StorageClass   = { fg = p.keyword, italic = true },
    Structure      = { fg = p.type },
    Typedef        = { fg = p.type, italic = true },
    Special        = { fg = p.regex },
    SpecialChar    = { fg = p.regex },
    Tag            = { fg = p.type },
    Delimiter      = { fg = p.fg3 },
    Debug          = { fg = p.warn },
    Underlined     = { fg = p.info, underline = true },
    Ignore         = { fg = p.fg4 },
    Error          = { fg = p.danger, bold = true },
    Todo           = { fg = p.bg, bg = p.accent, bold = true },

    -- ── treesitter ──
    ['@variable']           = { fg = p.fg },
    ['@variable.builtin']   = { fg = p.constant, italic = true },
    ['@variable.parameter'] = { fg = p.fg },
    ['@variable.member']    = { fg = p.fg },
    ['@constant']           = { fg = p.constant },
    ['@constant.builtin']   = { fg = p.constant },
    ['@constant.macro']     = { fg = p.constant, italic = true },
    ['@module']             = { fg = p.type },
    ['@label']              = { fg = p.keyword },
    ['@string']             = { fg = p.string },
    ['@string.escape']      = { fg = p.regex },
    ['@string.regexp']      = { fg = p.regex },
    ['@string.special']     = { fg = p.regex },
    ['@character']          = { fg = p.string },
    ['@character.special']  = { fg = p.regex },
    ['@number']             = { fg = p.number },
    ['@boolean']            = { fg = p.number },
    ['@float']              = { fg = p.number },
    ['@function']           = { fg = p.func },
    ['@function.builtin']   = { fg = p.func, italic = true },
    ['@function.call']      = { fg = p.func },
    ['@function.macro']     = { fg = p.constant, italic = true },
    ['@function.method']    = { fg = p.func },
    ['@function.method.call'] = { fg = p.func },
    ['@constructor']        = { fg = p.type },
    ['@operator']           = { fg = p.fg3 },
    ['@keyword']            = { fg = p.keyword },
    ['@keyword.function']   = { fg = p.keyword, italic = true },
    ['@keyword.operator']   = { fg = p.keyword },
    ['@keyword.return']     = { fg = p.keyword, italic = true },
    ['@keyword.import']     = { fg = p.keyword, italic = true },
    ['@keyword.exception']  = { fg = p.danger },
    ['@keyword.conditional']= { fg = p.keyword },
    ['@keyword.repeat']     = { fg = p.keyword },
    ['@keyword.coroutine']  = { fg = p.keyword, italic = true },
    ['@type']               = { fg = p.type },
    ['@type.builtin']       = { fg = p.type, italic = true },
    ['@type.definition']    = { fg = p.type },
    ['@attribute']          = { fg = p.constant, italic = true },
    ['@property']           = { fg = p.fg },
    ['@punctuation']        = { fg = p.fg3 },
    ['@punctuation.delimiter'] = { fg = p.fg3 },
    ['@punctuation.bracket'] = { fg = p.fg2 },
    ['@punctuation.special'] = { fg = p.keyword },
    ['@comment']            = { fg = p.comment, italic = true },
    ['@comment.todo']       = { fg = p.bg, bg = p.accent, bold = true },
    ['@comment.note']       = { fg = p.bg, bg = p.info, bold = true },
    ['@comment.warning']    = { fg = p.bg, bg = p.warn, bold = true },
    ['@comment.error']      = { fg = p.bg, bg = p.danger, bold = true },
    ['@tag']                = { fg = p.type },
    ['@tag.attribute']      = { fg = p.number, italic = true },
    ['@tag.delimiter']      = { fg = p.fg3 },
    ['@markup.heading']     = { fg = p.func, bold = true },
    ['@markup.heading.1']   = { fg = p.func, bold = true },
    ['@markup.heading.2']   = { fg = p.accent2, bold = true },
    ['@markup.heading.3']   = { fg = p.type, bold = true },
    ['@markup.strong']      = { fg = p.fg, bold = true },
    ['@markup.italic']      = { fg = p.fg, italic = true },
    ['@markup.strikethrough'] = { fg = p.fg3, strikethrough = true },
    ['@markup.underline']   = { fg = p.fg, underline = true },
    ['@markup.quote']       = { fg = p.fg3, italic = true },
    ['@markup.math']        = { fg = p.regex },
    ['@markup.link']        = { fg = p.info, underline = true },
    ['@markup.link.label']  = { fg = p.info },
    ['@markup.link.url']    = { fg = p.info, underline = true },
    ['@markup.raw']         = { fg = p.regex },
    ['@markup.raw.block']   = { fg = p.regex, bg = p.bg2 },
    ['@markup.list']        = { fg = p.keyword },
    ['@markup.list.checked']    = { fg = p.success },
    ['@markup.list.unchecked']  = { fg = p.fg3 },
    ['@diff.plus']          = { fg = p.success },
    ['@diff.minus']         = { fg = p.danger },
    ['@diff.delta']         = { fg = p.warn },

    -- ── LSP semantic tokens ──
    ['@lsp.type.class']         = { fg = p.type },
    ['@lsp.type.decorator']     = { fg = p.constant, italic = true },
    ['@lsp.type.enum']          = { fg = p.type },
    ['@lsp.type.enumMember']    = { fg = p.constant },
    ['@lsp.type.function']      = { fg = p.func },
    ['@lsp.type.interface']     = { fg = p.type },
    ['@lsp.type.macro']         = { fg = p.constant, italic = true },
    ['@lsp.type.method']        = { fg = p.func },
    ['@lsp.type.namespace']     = { fg = p.type },
    ['@lsp.type.parameter']     = { fg = p.fg },
    ['@lsp.type.property']      = { fg = p.fg },
    ['@lsp.type.struct']        = { fg = p.type },
    ['@lsp.type.type']          = { fg = p.type },
    ['@lsp.type.typeParameter'] = { fg = p.type, italic = true },
    ['@lsp.type.variable']      = { fg = p.fg },
    ['@lsp.mod.readonly']       = { fg = p.constant },
    ['@lsp.mod.deprecated']     = { fg = p.fg3, strikethrough = true },

    -- ── diagnostics ──
    DiagnosticError = { fg = p.danger },
    DiagnosticWarn  = { fg = p.warn },
    DiagnosticInfo  = { fg = p.info },
    DiagnosticHint  = { fg = p.accent },
    DiagnosticOk    = { fg = p.success },
    DiagnosticVirtualTextError = { fg = p.danger, bg = p.bg2 },
    DiagnosticVirtualTextWarn  = { fg = p.warn,   bg = p.bg2 },
    DiagnosticVirtualTextInfo  = { fg = p.info,   bg = p.bg2 },
    DiagnosticVirtualTextHint  = { fg = p.accent, bg = p.bg2 },
    DiagnosticUnderlineError = { sp = p.danger, undercurl = true },
    DiagnosticUnderlineWarn  = { sp = p.warn,   undercurl = true },
    DiagnosticUnderlineInfo  = { sp = p.info,   undercurl = true },
    DiagnosticUnderlineHint  = { sp = p.accent, undercurl = true },

    -- ── git signs ──
    GitSignsAdd    = { fg = p.success },
    GitSignsChange = { fg = p.warn },
    GitSignsDelete = { fg = p.danger },
    GitSignsAddNr    = { fg = p.success },
    GitSignsChangeNr = { fg = p.warn },
    GitSignsDeleteNr = { fg = p.danger },

    -- ── telescope ──
    TelescopeBorder         = { fg = p.border, bg = p.bg2 },
    TelescopePromptBorder   = { fg = p.accent, bg = p.bg2 },
    TelescopePromptTitle    = { fg = p.bg, bg = p.accent, bold = true },
    TelescopePreviewTitle   = { fg = p.bg, bg = p.type, bold = true },
    TelescopeResultsTitle   = { fg = p.fg2, bg = p.bg2 },
    TelescopeNormal         = { fg = p.fg, bg = p.bg2 },
    TelescopeMatching       = { fg = p.accent, bold = true },
    TelescopeSelection      = { fg = p.fg, bg = p.bg3, bold = true },

    -- ── nvim-tree / neo-tree ──
    NvimTreeNormal      = { fg = p.fg2, bg = p.bg2 },
    NvimTreeRootFolder  = { fg = p.accent, bold = true },
    NvimTreeFolderName  = { fg = p.fg },
    NvimTreeOpenedFolderName = { fg = p.fg, bold = true },
    NvimTreeFolderIcon  = { fg = p.warn },
    NvimTreeIndentMarker = { fg = p.bg3 },
    NvimTreeGitDirty    = { fg = p.warn },
    NvimTreeGitNew      = { fg = p.success },
    NvimTreeGitDeleted  = { fg = p.danger },

    -- ── cmp / completion ──
    CmpItemAbbrMatch          = { fg = p.accent, bold = true },
    CmpItemAbbrMatchFuzzy     = { fg = p.accent2, bold = true },
    CmpItemAbbrDeprecated     = { fg = p.fg4, strikethrough = true },
    CmpItemKindFunction       = { fg = p.func },
    CmpItemKindMethod         = { fg = p.func },
    CmpItemKindClass          = { fg = p.type },
    CmpItemKindInterface      = { fg = p.type },
    CmpItemKindKeyword        = { fg = p.keyword },
    CmpItemKindVariable       = { fg = p.fg },
    CmpItemKindConstant       = { fg = p.constant },
    CmpItemKindSnippet        = { fg = p.regex },
    CmpItemKindText           = { fg = p.string },
    CmpItemKindModule         = { fg = p.type },
    CmpItemKindFile           = { fg = p.fg },
    CmpItemKindFolder         = { fg = p.warn },

    -- ── indent-blankline ──
    IblIndent     = { fg = p.bg3 },
    IblScope      = { fg = p.fg4 },

    -- ── notify ──
    NotifyERRORBorder = { fg = p.danger },
    NotifyWARNBorder  = { fg = p.warn },
    NotifyINFOBorder  = { fg = p.info },
    NotifyDEBUGBorder = { fg = p.fg3 },
    NotifyTRACEBorder = { fg = p.constant },
    NotifyERRORTitle  = { fg = p.danger, bold = true },
    NotifyWARNTitle   = { fg = p.warn, bold = true },
    NotifyINFOTitle   = { fg = p.info, bold = true },
  })
end

return M
