# Bizarre Bone for i3
set $bizarre_bg #F5F2EA
set $bizarre_bg2 #EDE9DD
set $bizarre_fg #2B2B2B
set $bizarre_dim #4A4A4A
set $bizarre_accent #5F8A0F
set $bizarre_border #DDD8CB
client.focused          $bizarre_accent $bizarre_bg  $bizarre_fg  $bizarre_accent $bizarre_accent
client.focused_inactive $bizarre_border $bizarre_bg2 $bizarre_dim $bizarre_border $bizarre_border
client.unfocused        $bizarre_border $bizarre_bg2 $bizarre_dim $bizarre_border $bizarre_border
client.urgent           #B8276F $bizarre_bg #B8276F #B8276F #B8276F
client.placeholder      $bizarre_border $bizarre_bg2 $bizarre_dim $bizarre_border $bizarre_border
bar {
  colors {
    background $bizarre_bg
    statusline $bizarre_fg
    separator $bizarre_border
    focused_workspace $bizarre_accent $bizarre_accent #F9F8F2
    active_workspace $bizarre_bg2 $bizarre_bg2 $bizarre_fg
    inactive_workspace $bizarre_bg $bizarre_bg $bizarre_dim
    urgent_workspace #B8276F #B8276F #F9F8F2
  }
}
