# Bizarre Void for i3
set $bizarre_bg #0E0E0E
set $bizarre_bg2 #1A1A1A
set $bizarre_fg #E4E4E4
set $bizarre_dim #9C9C9C
set $bizarre_accent #C6FF24
set $bizarre_border #3D3D3D
client.focused          $bizarre_accent $bizarre_bg  $bizarre_fg  $bizarre_accent $bizarre_accent
client.focused_inactive $bizarre_border $bizarre_bg2 $bizarre_dim $bizarre_border $bizarre_border
client.unfocused        $bizarre_border $bizarre_bg2 $bizarre_dim $bizarre_border $bizarre_border
client.urgent           #FF6F77 $bizarre_bg #FF6F77 #FF6F77 #FF6F77
client.placeholder      $bizarre_border $bizarre_bg2 $bizarre_dim $bizarre_border $bizarre_border
bar {
  colors {
    background $bizarre_bg
    statusline $bizarre_fg
    separator $bizarre_border
    focused_workspace $bizarre_accent $bizarre_accent #0E0E0E
    active_workspace $bizarre_bg2 $bizarre_bg2 $bizarre_fg
    inactive_workspace $bizarre_bg $bizarre_bg $bizarre_dim
    urgent_workspace #FF6F77 #FF6F77 #0E0E0E
  }
}
