# Bizarre Bone for Rio
[fonts]
family = "Monaspace Neon"
size = 14

[colors]
background = "#F5F2EA"
foreground = "#2B2B2B"
cursor = "#5F8A0F"
selection-background = "#D4E89F"
selection-foreground = "#0E0E0E"
black = "#2B2B2B"
red = "#C13039"
green = "#3F7A1F"
yellow = "#9F4A0E"
blue = "#1F4FB0"
magenta = "#7E2A9A"
cyan = "#0F6E6E"
white = "#545454"
light-black = "#726D61"
light-red = "#C63947"
light-green = "#4A7409"
light-yellow = "#94631C"
light-blue = "#386EB6"
light-magenta = "#95559F"
light-cyan = "#397777"
light-white = "#0E0E0E"
