# Bizarre Bone - Alacritty
[colors.primary]
background = "#F5F2EA"
foreground = "#2B2B2B"

[colors.cursor]
text = "#0E0E0E"
cursor = "#5F8A0F"

[colors.selection]
text = "#0E0E0E"
background = "#D4E89F"

[colors.normal]
black = "#2B2B2B"
red = "#C13039"
green = "#3F7A1F"
yellow = "#9F4A0E"
blue = "#1F4FB0"
magenta = "#7E2A9A"
cyan = "#0F6E6E"
white = "#545454"

[colors.bright]
black = "#726D61"
red = "#C63947"
green = "#4A7409"
yellow = "#94631C"
blue = "#386EB6"
magenta = "#95559F"
cyan = "#397777"
white = "#0E0E0E"

[font]
normal = { family = "Monaspace Neon" }
